### ISSUE TITLE
PlatformIO build fails

### ISSUE THREAD

**Issue by borpin** [vlast3k/vThingCO2#1]
When attempting to build via PlatformIO it fails with the following error;

private
static uint8_t txBuffer[];
^
lib\I2CHelper\I2CHelper.cpp:211:54: error: within this context
ret = twi_writeTo(TwoWire::txAddress, TwoWire::txBuffer, TwoWire::txBufferLength, sendStop);
^
In file included from lib\I2CHelper/I2CHelper.hpp:3:0,

from lib\I2CHelper\I2CHelper.cpp:1:
C:\Users\Brian\.platformio\packages\framework-arduinoespressif8266\libraries\Wire/Wire.h:44:20: error: 'uint8_t TwoWire::txBufferLength' 
is private
static uint8_t txBufferLength;
^
lib\I2CHelper\I2CHelper.cpp:211:73: error: within this context
ret = twi_writeTo(TwoWire::txAddress, TwoWire::txBuffer, TwoWire::txBufferLength, sendStop);
^
*** [.pioenvs\nodemcuv2\lib\I2CHelper\I2CHelper.o] Error 1

**Comment by Egyras** [comment]
Same issue trying to build for NodeMCU

**Comment by vlast3k** [comment]
hmm, are you using the latest revision?
this isn't called on line 211 but 221 or so and is inside an #ifdef block
uint8_t I2CHelper::slowEndTransmission(uint8_t sendStop) {
  #ifdef SLOWWIRE
    int8_t ret;
    for (int i=0; i < 5; i++) {
      ret = twi_writeTo(TwoWire::txAddress, TwoWire::txBuffer, TwoWire::txBufferLength, sendStop);
      if (ret == 4) {
        delay(20);
        i2cSlowWireStatus();
        i2cHigh();


so unless you defined sLOWWIRE you shouldn't get there

**Comment by Egyras** [comment]
Second try....


In file included from lib\I2CHelper/I2CHelper.hpp:3:0,
from lib\I2CHelper\I2CHelper.cpp:1:
C:\Users\Vaikis\.platformio\packages\framework-arduinoespressif8266\libraries\Wire/Wire.h: In static member function 'static uint8_t I2CHelper::slowEndTransmission(uint8_t)':
C:\Users\Vaikis\.platformio\packages\framework-arduinoespressif8266\libraries\Wire/Wire.h:41:20: error: 'uint8_t TwoWire::txAddress' is private
static uint8_t txAddress;
^
lib\I2CHelper\I2CHelper.cpp:222:34: error: within this context
ret = twi_writeTo(TwoWire::txAddress, TwoWire::txBuffer, TwoWire::txBufferLength, sendStop);
^
In file included from lib\I2CHelper/I2CHelper.hpp:3:0,
from lib\I2CHelper\I2CHelper.cpp:1:
C:\Users\Vaikis\.platformio\packages\framework-arduinoespressif8266\libraries\Wire/Wire.h:42:20: error: 'uint8_t TwoWire::txBuffer []' is private
static uint8_t txBuffer[];
^
lib\I2CHelper\I2CHelper.cpp:222:54: error: within this context
ret = twi_writeTo(TwoWire::txAddress, TwoWire::txBuffer, TwoWire::txBufferLength, sendStop);
^
In file included from lib\I2CHelper/I2CHelper.hpp:3:0,
from lib\I2CHelper\I2CHelper.cpp:1:
C:\Users\Vaikis\.platformio\packages\framework-arduinoespressif8266\libraries\Wire/Wire.h:44:20: error: 'uint8_t TwoWire::txBufferLength' is private
static uint8_t txBufferLength;
^
lib\I2CHelper\I2CHelper.cpp:222:73: error: within this context
ret = twi_writeTo(TwoWire::txAddress, TwoWire::txBuffer, TwoWire::txBufferLength, sendStop);
^
*** [.pioenvs\nodemcuv2\libea8\I2CHelper\I2CHelper.cpp.o] Error 1
================================================================== [ERROR] Took 17.06 seconds ==================================================================
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

**Comment by Egyras** [comment]
did you used different wire.h library ? Iam using latest library and your GIT repo.

**Comment by vlast3k** [comment]
yeah, i've modified it a bit to expose some methods, but this was the purpose of the define, to only use this functionality in case the unmodified librariy is there.. and rather the twi.h or something else
i also did quite a lot of other changes in other core files to free up some memory of some static stuff, so currently it is rather unlikely to be able to build it on your own
i have to spend some time to somehow publish this, as currently it is just on mylaptop, and as soon as it fails it is gone :(
though i am not sure when i will be able to

imo the ESPEasy library is they way to go... it is already much more advanced, so if i ever continue with this it would be to use the ESPEasy for my tasks

**Comment by Egyras** [comment]
Maybe you can help to add Figaro CDM7160 sensor to ESPEasy as you wrote libraby for it, there is some interest: http://www.letscontrolit.com/forum/viewtopic.php?f=5&t=4851
Thanks !

**Comment by vlast3k** [comment]
thanks, i've replied to the thread there
